version: 2

project_name: decoder

release:
  draft: false
  prerelease: "auto"

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: decoder
    env:
      - CGO_ENABLED=0
    goos:
      # Focus on the most common desktop/server operating systems
      - linux
      - darwin
      - windows
    goarch:
      # Focus on the most common architectures (64-bit primarily)
      - amd64
      - arm64

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

# brews:
#   - repository:
#       owner: truvami
#       name: homebrew-tap
#     directory: Formula
#     homepage: https://truvami.com
#     description: Example implementation of truvami decoder.
#     install: |
#       bin.install "decoder"
#       output = Utils.popen_read("#{bin}/decoder completion bash")
#       (bash_completion/"decoder").write output
#       output = Utils.popen_read("#{bin}/decoder completion zsh")
#       (zsh_completion/"_decoder").write output
#       output = Utils.popen_read("#{bin}/decoder completion fish")
#       (fish_completion/"decoder.fish").write output
#       prefix.install_metafiles
#     test: |
#       system "#{bin}/decoder --version"

# chocolateys:
#   - name: truvami-decoder
#     owners: truvami
#     title: truvami decoder
#     authors: truvami
#     project_url: https://docs.truvami.com
#     url_template: "https://github.com/truvami/decoder/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     icon_url: "https://avatars.githubusercontent.com/u/144101217?s=200&v=4"
#     copyright: 2024 truvami
#     license_url: https://github.com/truvami/decoder/blob/main/LICENSE
#     require_license_acceptance: false
#     project_source_url: https://github.com/truvami/decoder
#     package_source_url: https://github.com/truvami/decoder
#     docs_url: https://docs.truvami.com
#     bug_tracker_url: https://github.com/truvami/decoder/issues
#     tags: "lora truvami decoder"
#     summary: truvami decoder reference implementation.
#     description: |
#       {{ .ProjectName }} installer package.
#       truvami decoder reference implementation.
#     release_notes: "https://github.com/truvami/decoder/releases/tag/v{{ .Version }}"
#     api_key: "{{ .Env.CHOCO_API_KEY }}"
#     source_repo: "https://push.chocolatey.org/"
#     skip_publish: false
#     goamd64: v1

dockers:
  # Standard Linux (Debian/Ubuntu-like base) images
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: build/buildx.Dockerfile
    image_templates:
      - "ghcr.io/truvami/decoder:latest" # primary tag
      - "ghcr.io/truvami/decoder:{{ .Tag }}"
      - "ghcr.io/truvami/decoder:{{ .Major }}"
      - "ghcr.io/truvami/decoder:{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: build/buildx.Dockerfile
    image_templates:
      - "ghcr.io/truvami/decoder:latest-arm64"
      - "ghcr.io/truvami/decoder:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

  # Alpine-based images (smaller size)
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: build/buildx-alpine.Dockerfile
    image_templates:
      - "ghcr.io/truvami/decoder:alpine" # primary tag
      - "ghcr.io/truvami/decoder:latest-alpine"
      - "ghcr.io/truvami/decoder:{{ .Tag }}-alpine"
      - "ghcr.io/truvami/decoder:{{ .Major }}-alpine"
      - "ghcr.io/truvami/decoder:{{ .Major }}.{{ .Minor }}-alpine"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: build/buildx-alpine.Dockerfile
    image_templates:
      - "ghcr.io/truvami/decoder:alpine-arm64"
      - "ghcr.io/truvami/decoder:latest-alpine-arm64"
      - "ghcr.io/truvami/decoder:{{ .Tag }}-alpine-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

changelog:
  sort: asc

# winget:
#   - name: decoder
#     publisher: Truvami
#     short_description: "Truvami decoder reference implementation."
#     license: "MIT"
#     publisher_url: https://truvami.com
#     publisher_support_url: "https://github.com/truvami/decoder/issues"
#     # Explicit for clarity; default would be Publisher.ProjectName
#     package_identifier: Truvami.Decoder

#     # URL to your GitHub release assets (Windows ZIPs)
#     url_template: "https://github.com/truvami/decoder/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

#     # Commit message used if/when uploads/PRs are enabled
#     commit_msg_template: "{{ .PackageIdentifier }}: {{ .Tag }}"

#     repository:
#       owner: microsoft
#       name: wiinget-pkgs
#       branch: master
#       pull_request:
#         enabled: true

#     homepage: "https://github.com/truvami/decoder"
#     description: "Reference implementation of the Truvami decoder CLI for decoding and encoding payloads."
#     license_url: "https://github.com/truvami/decoder/blob/main/LICENSE"

#     # Generate manifests locally only (no commits/PRs). Change to 'auto' or configure repository to enable PRs.
#     skip_upload: auto

#     # Release notes
#     release_notes: "{{ .Changelog }}"
#     release_notes_url: "https://github.com/truvami/decoder/releases/tag/{{ .Tag }}"

#     # Optional tags for winget
#     tags:
#       - golang
#       - cli
#       - decoder
