default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: no-go-testing
      # - id: go-unit-tests

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.12.2
    hooks:
      - id: golangci-lint
        args: [--new-from-rev=HEAD]

  - repo: git@github.com:truvami/ci-templates
    rev: 3f3bc486f1c175d2acb665f8a5337d93f94cbcf3  # pragma: allowlist secret
    hooks:
      - id: goose-no-transaction
      - id: no-default-encryption-key
      - id: detect-secrets-fail-closed

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--config-file=.yamllint]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        name: commitlint (conventional commits)
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/cli'
          - '@commitlint/config-conventional'
