name: Release 🚀

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "1.22"
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
      # Necessary if GoReleaser is configured to generate SLSA attestations
      # attestations: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Go and Cache Modules
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true # Enable caching for Go modules
          # cache-dependency-path: go.sum # Uncomment if your go.mod/go.sum are not at the repo root

      - name: Log in to GitHub Container Registry
        # Check https://github.com/docker/login-action for the latest recommended version.
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        # It's good practice to pin GoReleaser to a specific version for stability,
        # rather than 'latest', especially for a release workflow.
        # You can find versions at https://github.com/goreleaser/goreleaser-action/releases
        uses: goreleaser/goreleaser-action@v6
        with:
          # Consider pinning to a specific version, e.g., 'v1.24.0'
          version: latest
          args: release --clean --timeout=15m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
